import "bootstrap/dist/css/bootstrap.min.css";
import ImportBsJS from './bootstrap';

/**import CustomCursor from './_components/CustomCursor';**/

import './globals.css';

import Script from 'next/script';

import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';


const inter = DM_Sans ({ 
    subsets: ['latin'],
    weight:['300','400','500','700', '900'],
    variable: '--font-spspace-groteskrotesk',
    display: 'swap',
})

export const metadata: Metadata = {
  title: 'Hello, this is Ryan Angelo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ImportBsJS/>
        {children}
        <Script 
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossOrigin="anonymous"
          />
        <Script 
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossOrigin="anonymous"
        />
      </body>
    </html>
  )
}
