import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter ({ 
    subsets: ['latin'],
    weight:['300','400','500','700', '900'],
    variable: '--font-spspace-groteskrotesk',
    display: 'swap',
})

export const metadata: Metadata = {
  title: 'Hello, this is Ryan Angelo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
